name: myabsensi_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^1.5.0
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.14.2
  open_file: ^3.5.10
  excel: ^2.0.7
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.4
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  google_mlkit_face_detection: ^0.11.0
  geocoding: ^2.1.0
  url_launcher: ^6.1.14
  device_info_plus: ^10.1.0
  camera: ^0.11.0+2
  image_cropper: ^12.2.0
  cupertino_icons: ^1.0.8
  camera_web: ^0.3.2
  simple_web_camera: ^1.0.11
  cross_file: ^0.3.3+4
  file_picker: ^8.1.2
  path_provider: ^2.1.0
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  flutter_native_splash: ^2.4.0 # ← pindah ke dependencies agar bisa dipanggil di main.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# ─────────────────────────────────────────────────────────────
# Flutter Native Splash — sejajar dengan flutter:, bukan di dalam
# ─────────────────────────────────────────────────────────────
flutter_native_splash:
  # Full image background (Android < 12 & iOS)
  background_image: assets/images/splash_screen.png
  color: "#FFFFFF" # fallback warna jika gambar belum load

  # Android 12+ — tidak support full bg image, pakai logo + warna
  android_12:
    image: assets/images/logo_transparan.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

  web: false

# ─────────────────────────────────────────────────────────────
# Flutter Launcher Icon
# ─────────────────────────────────────────────────────────────

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_karyaone.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_karyaone.png"

# ─────────────────────────────────────────────────────────────
# Flutter
# ─────────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
